paths:
  input_folder: "input-csv"
  processed_folder: "processed"
  output_folder: "output-csv"
  category_file: "categoryrules.yaml"
  model_file: "models\\expense_categorizer_model.pkl"

app:
  use_ml_model: true